AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  drawing-with-dynamodb

  SAM Template for drawing-with-dynamodb

Globals:
  Function:
    Timeout: 3

Resources:
  PutDrawingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: put_drawing/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - Statement:
        - Sid: PutItemAndBatchWritePolicy
          Effect: Allow
          Action:
          - dynamodb:PutItem
          - dynamodb:BatchWriteItem
          Resource: '*'
      Events:
        PutDrawing:
          Type: Api
          Properties:
            Path: /putDrawing
            Method: post
  GetDrawingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_drawing/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - Statement:
        - Sid: PutItemAndBatchWritePolicy
          Effect: Allow
          Action:
          - dynamodb:Scan
          Resource: '*'
      Events:
        PutDrawing:
          Type: Api
          Properties:
            Path: /getDrawing
            Method: post
  GetAllDrawingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_all_drawings/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - Statement:
        - Sid: PutItemAndBatchWritePolicy
          Effect: Allow
          Action:
          - dynamodb:Scan
          Resource: '*'
      Events:
        PutDrawing:
          Type: Api
          Properties:
            Path: /getAllDrawings
            Method: get

Outputs:
  DrawWithDynamodbApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
